---
version: "2"
run:
  tests: false
linters:
  default: none
  enable:
    - depguard
    - dogsled
    - goconst
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - staticcheck
    - unconvert
    - unused
  settings:
    dogsled:
      max-blank-identifiers: 3
    nolintlint:
      require-explanation: false
      require-specific: false
      allow-unused: false
    depguard:
      rules:
        main:
          list-mode: lax
          allow:
            - $gostd
            - github.com/cosmos-sdk
            - github.com/cometbft
            - google.golang.org
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        text: Use of weak random number generator
      - linters:
          - gosec
        text: 'G115:'
      - linters:
          - staticcheck
        text: 'ST1003:'
      - linters:
          - staticcheck
        text: 'ST1016:'
      - linters:
          - staticcheck
        path: .
        text: 'SA1019:'
      - linters:
          - staticcheck
        path: .
        text: 'QF1008:'
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 10000
  max-same-issues: 10000
formatters:
  enable:
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
