name: Build SimApp
#  This workflow is run on pushes to main & every Pull Requests where a .go, .mod, .sum have been changed
on:
  pull_request:
  push:
    branches:
      - main
      - release/**
permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}-build
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-arch: ["amd64", "arm", "arm64"]
    steps:
      - uses: actions/checkout@v4
      - run: |-
          go_version=$(grep -E '^go [0-9]{1,}.[0-9]{1,}(.[0-9]{1,})?$' "go.mod" | cut -d ' ' -f 2 | tr -d '\n')
          echo "GOVERSION=${go_version}" >> $GITHUB_ENV
      - uses: actions/setup-go@v5
        with:
          go-version: "${{ env.GOVERSION }}"
          check-latest: true
      - uses: technote-space/get-diff-action@v6.1.1
        id: git_diff
        with:
          PATTERNS: |
            **/*.go
            go.mod
            go.sum
            **/go.mod
            **/go.sum
            **/Makefile
            Makefile
      - name: Build
        if: env.GIT_DIFF
        run: GOARCH=${{ matrix.go-arch }} make build
      - name: Build Legacy
        if: env.GIT_DIFF
        run: GOARCH=${{ matrix.go-arch }} COSMOS_BUILD_OPTIONS=legacy make build
